# Generated by Django 5.2.13 on 2026-05-04 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'barbers',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SERVICE', 'Service'), ('PRODUCT', 'Product')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'items',
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='items_price_gte_0'), models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='items_stock_gte_0'), models.CheckConstraint(condition=models.Q(('commission_rate__gte', 0)), name='items_commission_rate_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_id', models.CharField(max_length=36, unique=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('VOIDED', 'Voided')], max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.barber')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.barber')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.item')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.transaction')),
            ],
            options={
                'db_table': 'transaction_items',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transactions_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='transactions_discount_gte_0'),
        ),
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['barber', 'created_at'], name='tx_items_barber_created_idx '),
        ),
        migrations.AddConstraint(
            model_name='transactionitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='tx_items_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='transactionitem',
            constraint=models.CheckConstraint(condition=models.Q(('price_at_sale__gte', 0)), name='tx_items_price_at_sale_gte_0'),
        ),
    ]
