# Generated by Django 5.2.13 on 2026-05-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
